### ISSUE TITLE
CID 1401053:  Control flow issues  (NESTING_INDENT_MISMATCH)

### ISSUE THREAD

**Issue by fgsch** [madler/zlib#262] opened 2017-05-12 14:11 UTC
```
/lib/libvgz/deflate.c: 605 in deflateParams()
599     }
600     if (s->level != level) {
601         if (s->level == 0 && s->matches != 0) {
602             if (s->matches == 1)
603                 slide_hash(s);
604             else
>>> CID 1401053:  Control flow issues  (NESTING_INDENT_MISMATCH)
>>> The macro on this line expands into multiple statements, only
>>> the first of which is nested within the preceding parent while
>>> the rest are not.
605                 CLEAR_HASH(s);
606             s->matches = 0;
607         }
608         s->level = level;
609         s->max_lazy_match   = configuration_table[level].max_lazy;
610         s->good_match       = configuration_table[level].good_length;
```

Spotted by Coverity.

Our fix at https://github.com/varnishcache/varnish-cache/commit/ea111153098fe636f7c42ab8da4efdc5954e894e.

**Comment by tbeu** [comment] 2017-08-15 07:20
Duplicate of #261.

**Closed** 2017-08-22 10:31 UTC
