### ISSUE TITLE
Build failed with cr32 errors in Windows zlibvc 1.2.12 - Win32/x86

### ISSUE THREAD

**Issue by SivaShankar1925** [madler/zlib#629] opened 2022-04-05 11:31 UTC
After removing masm & asm references, as per this PR -[ https://github.com/madler/zlib/pull/619](
It is building successfully with x64 , but with Win32/x86 it is throwing a below exception
I'm using VS2017

1>crc32.c(1089): error C2708: 'crc32_combine64': actual parameters length in bytes differs from previous call or reference
1> crc32.c(1072): note: see declaration of 'crc32_combine64'
1> crc32.c(1106): error C2708: 'crc32_combine_gen64': actual parameters length in bytes differs from previous call or reference
1> crc32.c(1093): note: see declaration of 'crc32_combine_gen64'
1> crc32.c(1110): error C2373: 'crc32_combine_op': redefinition; different type modifiers
1> zlib.h(1768): note: see declaration of 'crc32_combine_op'

**Comment by SLDiggie** [comment] 2022-04-07 11:10
Dupe of https://github.com/madler/zlib/issues/620

**Comment by PCIIT** [comment] 2022-04-08 04:22
Hi Team , i am planning to install zlib1.2.12 but after downloaded zlib1.2.12 , i can see missing the  .dll file ( zlib.dll ,zlib1.dll) .so where i can .dll file.

**Comment by tbeu** [comment] 2022-04-10 11:30
Conan Center has the binaries available: https://conan.io/center/zlib

**Comment by PCIIT** [comment] 2022-04-11 03:44
not able to download file..

**Comment by tbeu** [comment] 2022-09-05 19:29
Resolved by 7ecf7c7458578d05a20fa481436dd5c58db112f7 and 6c532a8e8a2fcedc4abbe2378dd26b5d89cf1c4a.

**Comment by madler** [comment] 2022-10-06 22:12
Closing, per @tbeu.

**Closed by madler** 2022-10-06 22:12 UTC
