### ISSUE TITLE
zlib 1.2.11 crashes in 'inffas32.asm' if 'avail_out' CHUNK size > 257 

### ISSUE THREAD

**Issue by vanillycpp** [madler/zlib#249] opened 2017-04-07 14:40 UTC
Hi! I have some test data in 
RFC 1951 (deflate compressed format) (with no header)
http://tilesearth.com/tmp/def_log.txt

Im trying to decompress it
here is my code

----------------------------------------------------------------------
`#define ZLIB_WINAPI`
`#define CHUNK 258`

`#include <stdio.h>`
`#include <fstream>`
`#include "zlib.h"`

`int main()`
`{`
	`char buf[50];`
	`char res[CHUNK];`
  
        std::ifstream file;
	file.open("def_log.txt", std::ios::binary | std::ios::ate);

	std::streamsize size = file.tellg();
	file.seekg(0, std::ios::beg);

	if (file.is_open())
	{
		file.read((char*)buf, size);
		file.close();
	}

	z_stream strm;
	strm.zalloc = Z_NULL;
	strm.zfree = Z_NULL;
	strm.opaque = Z_NULL;
	strm.avail_in = size;
	strm.next_in = (Bytef *)buf;
	strm.avail_out = (uInt)CHUNK;
	strm.next_out = (Bytef *)res;

	if (inflateInit2(&strm, -MAX_WBITS) == Z_OK)
	{
		inflate(&strm, Z_NO_FLUSH);
		inflateEnd(&strm);
	}
    return 0;
`}`

----------------------------------------------------------------------

so, in case when `#define CHUNK 257`
everything works fine
but, if I change this `#define CHUNK 258`
program crashes at `inffas32.asm line 669`
![zlib_crach](https://cloud.githubusercontent.com/assets/12745329/24803370/afc38d7e-1bb3-11e7-9b93-54c1eb05bda4.jpg)

could you help me to understand what is wrong?

**Comment by tbeu** [comment] 2017-04-10 07:31
Duplicate of #200.

**Comment by vanillycpp** [comment] 2017-04-10 18:17
Thanks a lot!
Didnt find it

**Closed** 2017-04-10 18:17 UTC

**Comment by rhuijben** [comment] 2017-04-11 12:20
Don't forget to check #41 as well.
