### ISSUE TITLE
GCC warning that sounds like a bug regarding deflate.c:603

### ISSUE THREAD

**Issue by coypoop** [madler/zlib#415] opened 2019-04-03 11:27 UTC
While building with a wide variety of systems, came across this GCC 8.2.0 warning:

````
deflate.c: In function 'deflateParams':
deflate.c:602:28: warning: macro expands to multiple statements [-Wmultistatement-macros]
                 CLEAR_HASH(s);
                            ^
deflate.c:193:5: note: in definition of macro 'CLEAR_HASH'
     s->head[s->hash_size-1] = NIL; \
     ^
deflate.c:601:13: note: some parts of macro expansion are not guarded by this 'else' clause
             else
             ^~~~
````

````
#define CLEAR_HASH(s) \
    s->head[s->hash_size-1] = NIL; \
    zmemzero((Bytef *)s->head, (unsigned)(s->hash_size-1)*sizeof(*s->head));
...
            if (s->matches == 1)
                slide_hash(s);
            else
                CLEAR_HASH(s);
````

this expands to:
````
            if (s->matches == 1)
                slide_hash(s);
            else
                s->head[s->hash_size-1] = NIL;
            zmemzero((Bytef *)s->head, (unsigned)(s->hash_size-1)*sizeof(*s->head));
````

This looks far from the intention!

changing the definition to use
````
#define CLEAR_HASH(s) \
do { \
s->head[s->hash_size-1] = NIL; \
zmemzero((Bytef *)s->head, (unsigned)(s->hash_size-1)*sizeof(*s->head)); \
} while(0)
````

Will do the expected thing under all circumstances, but I haven't looked at the code to know if this is correct!

**Comment by madler** [comment] 2019-04-04 18:17
That was fixed in https://github.com/madler/zlib/commit/38e8ce32afbaa82f67d992b9f3056f281fe69259

**Closed by madler** 2019-04-04 18:17 UTC

**Comment by coypoop** [comment] 2019-04-04 18:42
thanks!
sorry, I didn't realize the default branch is not the latest.

**Comment by tbeu** [comment] 2019-07-24 08:45
This is a duplicate of #207, #208, #261, #288, #327 and partially of #384.
