### ISSUE TITLE
minizip can create an archive up to 2GB

### ISSUE THREAD

**Issue by d0nc1h0t** [madler/zlib#671] opened 2022-07-01 09:33 UTC
When calling the fseek64_file_func function, an erroneous conversion of the 64-bit offset to 32 occurs.
```
static long ZCALLBACK fseek64_file_func (voidpf  opaque, voidpf stream, ZPOS64_T offset, int origin)
{
    ...

    if(FSEEKO_FUNC((FILE *)stream, (long)offset, fseek_origin) != 0)
                        ret = -1;

    return ret;
}
```

**Comment by MJindrova** [comment] 2022-09-02 10:08
I can confirm it for Win32/Win64 platform.
This change allow zip file with max size 2GiB.

**Comment by xtne6f** [comment] 2022-09-14 07:03
I also suffered from the bug and found this issue!
It must be an enbug by commit 2014a993addbc8f1b9785d97f55fd189792c2f78 .
I hope that it will be fixed as soon as possible ...

**Comment by madler** [comment] 2022-10-06 22:41
Fixed.

**Closed by madler** 2022-10-06 22:41 UTC

**Comment by xtne6f** [comment] 2022-10-15 08:59
Commit: 9b291c9f013f99ad494ffecf4295cb2f594a18e3 seems not to fix the issue at least on Win32, because `z_off_t` is `long` (32bit)  while `ZPOS64_T` is `long long` (64bit).

**Comment by gvollant** [comment] 2022-10-15 09:43
we probably must use z_off64_t
