### ISSUE TITLE
using gzoffset to check written file size differs with actual file size by 20 bytes

### ISSUE THREAD

**Issue by Displacer** [madler/zlib#417] opened 2019-04-11 13:16 UTC
I am trying to check actual compressed file size written this way:

gzflush(outputFIle, Z_FINISH);
actualFileSize = gzoffset(outputFIle);   // + 20 ?
gzclose(outputFIle);

Unfortunately resulting actual file size is 20 bytes more then gzoffset returns. Is it correct to add 20 bytes to gzoffset value to get actualFileSize? Is there a different method to get actual file size written?

**Comment by madler** [comment] 2019-04-11 19:46
It shouldn't do that. If not a bug, that is at least a bad behavior of closing after flushing. What is happening is that your `Z_FINISH` is correctly completing the gzip stream, writing the remaining compressed data and the gzip trailer. The reported `gzoffset()` is the correct length of that gzip stream. However the `gzclose()` is then writing _another_ empty gzip stream after that one, which is 20 bytes in length. (A ten-byte header, two bytes for the zero-length compressed data, and an eight-byte trailer.) That additional empty gzip stream is not necessary, and will be avoided in a future release.

**Comment by madler** [comment] 2019-04-14 00:12
Fixed by https://github.com/madler/zlib/commit/79baebe50e4d6b73ae1f8b603f0ef41300110aa3 .

**Closed by madler** 2019-04-14 00:12 UTC
