### ISSUE TITLE
configure includes wrong zconf.h in out-of-tree builds

### ISSUE THREAD

**Issue by dankegel** [madler/zlib#499] opened 2020-05-22 21:34 UTC
Out-of-tree compilation fails if you do out-of-tree cmake build and make build sequentially.

Evidently configure's out-of-tree build sometimes pulls in a stale zconf.h
(either the system's, or the default one checked into the top of the source tree)
rather than the one it generated.

**Comment by nmoinvaz** [comment] 2020-05-22 21:47
CI #492 should have out of source build to ensure that future CMake changes still work with out of source builds.

**Comment by dankegel** [comment] 2020-05-22 21:57
Oh, quite.  See https://github.com/dankegel/zlib/pull/5  :-)

**Comment by tbeu** [comment] 2020-05-25 18:17
Duplicate of #344.

**Comment by dankegel** [comment] 2020-05-25 18:22
No, not quite.  It's related, but even if there were no CMakeLists.txt at all, this bug would exist and be real.

**Comment by madler** [comment] 2024-01-20 01:34
Should be addressed by https://github.com/madler/zlib/commit/9404df5a1f35866d441e8033b34186ca42962ea9 .

**Closed by madler** 2024-01-20 01:34 UTC
