### ISSUE TITLE
Deflate failures confirmed in downstreams using 1.2.10 / 1.2.11

### ISSUE THREAD

**Issue by jeremyjh** [madler/zlib#206] opened 2017-01-20 00:20 UTC
Sorry this is not a more helpful bug report as I don't know the nature of the issue or have a simple test program but I thought I should leave it here in case it helps others. 

I found a problem this week in the Erlang `dialyzer` program on Arch Linux; it was not able to recognize its own file formats after an update.  I isolated the failure to the recent zlib update and then found someone else from the Arch forum had also found a [zlib problem in an SDL game](https://bbs.archlinux.org/viewtopic.php?id=222116).

@michelboaventura had also seen the `dialyzer` issue using 1.2.11 on gentoo, after hearing it was linked to zlib  he was kind enough to bisect the zlib commit history and isolated the fault to b516b4bdd7c0c9f0858adfebf732089014f7b282 (this is reported in this [thread](http://erlang.org/pipermail/erlang-bugs/2017-January/005206.html)). The same commit was confirmed to be where the issue was introduced in the manaplus game mentioned in the Arch thread.

**Comment by madler** [comment] 2017-01-20 01:43
Isolating it to that commit points to a problem in the application code, where it must be inadvertently stomping on the deflate state, e.g. with an out-of-bounds write into memory, or perhaps that the code is trying to use the deflate state after it has been closed. The only change that commit made was to check the integrity of the deflate structure more thoroughly on each call of a deflate* function.

**Comment by michelboaventura** [comment] 2017-01-20 01:55
Hi @madler,

If tested every change on that commit and figure out these two ifs which returned false before the commit started to return true afterwards:
https://github.com/madler/zlib/commit/b516b4bdd7c0c9f0858adfebf732089014f7b282#diff-327188edf18799ffbb5a51cc69f797e8R645
https://github.com/madler/zlib/commit/b516b4bdd7c0c9f0858adfebf732089014f7b282#diff-327188edf18799ffbb5a51cc69f797e8R1281

Checking what is now being checked on ``inflateStateCheck`` that wasn't I find out the issue is with the ``state->strm != strm`` bit. So they were probably equal but this wasn't checked until this commit.

May you guide me to better debug it? What is the issue with those two 'strm' being equal, and how the erlang code could have used it in a wrong way?

**Comment by sverker** [comment] 2017-01-20 15:52
The Erlang VM does a shallow memcpy of z_stream and commit https://github.com/madler/zlib/commit/b516b4bdd7c0c9f0858adfebf732089014f7b282
introduced a back pointer from the internal inflate_state to the (old deallocated) z_stream.

Seems inflateCopy()  is the solution and the correct way to do it.
This bug has existed since Erlang/OTP R16B03.

/Sverker, Erlang/OTP @ Ericsson

**Comment by madler** [comment] 2017-01-20 16:28
Thank you for the resolution. I will close this as it is not a zlib issue.

**Closed by madler** 2017-01-20 16:28 UTC

**Comment by jeremyjh** [comment] 2017-01-20 16:52
@madler thanks for your help!

**Comment by michelboaventura** [comment] 2017-01-21 19:57
Thank you @sverker and @madler for the help and thanks to @jeremyjh to help to pin point the issue.

**Comment by 4144** [comment] 2017-01-21 22:40
I am developer of this SDL game.
I tracked issue to libphysfs and zlib.

Here is zip archive with example: http://download.evolonline.org/manaplus/bug/bug.zip
Unpack it, and run ./run

Probably error in physfs, and i will report same issue to physfs developer.

**Comment by 4144** [comment] 2017-01-24 13:14
It was same issue in physfs. Replacing memcpy to inflateCopy fixed issues

**Comment by sverker** [comment] 2017-01-24 13:42
@4144 and don't forget to deallocate abandoned z_stream with inflateEnd.

**Comment by madler** [comment] 2017-01-24 19:52
Of course, if you're just going to copy it and then abandon the original, you could instead simply transfer the original.

**Comment by 4144** [comment] 2017-01-24 21:51
I think it's ok only with replacing memcpy to inflateCopy. But i not familar with zlib api.

Here is code with bug: https://hg.icculus.org/icculus/physfs/file/34ebe997c5c0/archivers/zip.c#l330
and here fix: http://download.evolonline.org/manaplus/bug/zip_seek.diff

Physfs devs still not responding...

**Comment by sverker** [comment] 2017-01-25 10:39
@madler I didn't find any support in the API to "transfer"  a z_stream.

**Comment by sverker** [comment] 2017-01-25 10:46
@4144 inflateCopy will give you two independent z_stream's and you need to deallocate them both, the original and the copy.

**Comment by sverker** [comment] 2017-01-25 11:00
@madler Maybe I misunderstood you. I have a stack allocated z_stream and I need to store it in a heap allocated structure i order to return back and do other work for a while. By transfer I thought you ment an optimized "inflateMove" operation that reuses (transfer) the internal_state to a new z_stream.

**Comment by madler** [comment] 2017-01-25 19:54
By "transfer" I mean simply provide the pointer. It sounded like someone was copying an inflate state, destroying the original, and proceeding to use the copy, when they could have just used the original instead without ever copying. I understand from your post that the state is on the stack of a routine that is returning, and so needs to be moved to a safer place. Then it makes sense to copy and immediately destroy the original.

**Comment by 4144** [comment] 2017-01-26 12:18
@sverker thanks, physfs patch updated.
