### ISSUE TITLE
Incorrect Minizip version shown to the user

### ISSUE THREAD

**Issue by blackandwhitebg** [madler/zlib#411] opened 2019-03-22 22:52 UTC
A minor issue about minizip -
The file

zlib/contrib/minizip/miniunz.c
is apparently from version 1.1

but in the "do_banner()" function, which displays the version to the user,
it's still "MiniUnz 1.01b"

**Comment by tbeu** [comment] 2019-04-02 20:52
Duplicate of #174.

**Comment by Neustradamus** [comment] 2022-10-12 01:02
@gvollant: What do you think?

**Comment by gvollant** [comment] 2022-10-15 08:32
I agree the #174 modification

**Comment by Neustradamus** [comment] 2024-01-21 11:18
@blackandwhitebg: I think that you can close this ticket?

Merged commit from #174 by @tbeu:
- https://github.com/madler/zlib/commit/88e50f170525c0a6237ca5ed4db0c620af366fe7

@madler: I think, it is needed to update again the version number with the latest CVE fix:
- https://github.com/madler/zlib/commits/develop/contrib/minizip

**Closed** 2024-01-21 17:35 UTC
